Version 1.3.13pre4-1

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -66,7 +66,7 @@ binary-arch: build install
 #	dh_installinfo
 	dh_installman kvqc2d.1
 	dh_link
-	dh_strip
+	dh_strip --dbg-package=kvqc2d-dbg
 	dh_compress
 	dh_fixperms
 #	dh_perl
@@ -84,9 +84,11 @@ version-check:
 	@AC_VERSION=$$(grep ^AC_INIT configure.ac | sed -e 's/^AC_INIT(\[[a-zA-Z0-9_.~]\+\], *\[//' -e 's/\], *\[[a-z@.-]\+\])//'); \
 	DEBIAN_VERSION=$$(head -n 1 debian/changelog | sed -e 's/^[a-z_0-9-]\+ (\([0-9]\+\.[a-zA-Z0-9_.~]\+\)-[^-)]).*$$/\1/'); \
 	if [ "x$$DEBIAN_VERSION" != "x$$AC_VERSION" ]; then \
-	    echo "Error: debian version '$$DEBIAN_VERSION' != version '$$AC_VERSION' from configure.ac"; exit 1; \
+	    echo "Error: debian version '$$DEBIAN_VERSION' != version '$$AC_VERSION' from configure.ac"; \
+	    if [ "x$$KVQC2D_BUILD_VERSION_CHECK" != "xNO" ]; then exit 1; fi \
 	fi; \
 	$(MAKE) -C src version_git.stamp; \
 	if grep -q "KVQC2D_VERSION_FULL.*_no_version" src/version_git.h; then \
-	    echo "Error: invalid version for packaging in src/version_git.h"; exit 1; \
+	    echo "Error: invalid version for packaging in src/version_git.h"; \
+	    if [ "x$$KVQC2D_BUILD_VERSION_CHECK" != "xNO" ]; then exit 1; fi \
 	fi
