Check version when packaging, and include version LOGINFO.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -18,7 +18,7 @@ CC=gcc-4.1
 # lets just keep going and see what happens ...
 
 configure: configure-stamp
-configure-stamp:
+configure-stamp: version-check
 	dh_testdir
 	autoreconf -i
 	./configure --prefix=/usr  --mandir=\$${prefix}/share/man --infodir=\$${prefix}/share/info  --localstatedir=/var --sysconfdir=/etc CFLAGS="$(CFLAGS)" CXXFLAGS="$(CXXFLAGS)"
@@ -82,3 +82,10 @@ binary-arch: build install
 
 binary: binary-indep binary-arch
 .PHONY: build clean binary-indep binary-arch binary install configure
+
+version-check:
+	@AC_VERSION=$$(grep ^AC_INIT configure.ac | sed -e 's/^AC_INIT(\[[a-zA-Z0-9_-]\+\], *\[//' -e 's/\], *\[[a-z@.-]\+\])//'); \
+	DEBIAN_VERSION=$$(head -n 1 debian/changelog | sed -e 's/^[a-z_0-9-]\+ (\([0-9]\+\.[0-9.a-zA-Z]\+\)-[^-)]).*$$/\1/'); \
+	if [ "x$$DEBIAN_VERSION" != "x$$AC_VERSION" ]; then \
+	    echo "Error: debian version '$$DEBIAN_VERSION' != version '$$AC_VERSION' from configure.ac"; exit 1; \
+	fi
